### ISSUE TITLE
Unrecognized function or variable 'minFilt2_v2'

### ISSUE THREAD

**Issue by kumarballapavan** [v1t0ry/Haziness-degree-evaluator#1]
While executing the module 'new_indicator_v5_opt.m', I am getting the following error.

Error: Unrecognized function or variable 'minFilt2_v2'

I request you to kindly look into this issue and provide the code for the 'minFilt2_v2' module or guide me in the right way.

Thank you.

**Comment by kumarballapavan** [comment]
I can skip this error by putting comments on that line.

% inImgGray = minFilt2_v2(inImgGray,sv);

Thank you.

**Comment by datngo93** [comment]
Thanks for your message~~

The function 'minFilt2_v2' realizes the spatial minimum filter, and it is identical to the function 'minFilt2_opt'. Therefore, please change 'minFilt2_v2' to 'minFilt2_opt' and run the code again!

Commenting this line out is not an option. I have fixed the code, you can simply download and run again.

**Comment by kumarballapavan** [comment]
Thank you, author.
