### ISSUE TITLE
Unrecognized function or variable 'featuresCalc_v2'.

### ISSUE THREAD

**Issue by kumarballapavan** [v1t0ry/Haziness-degree-evaluator#2]
While executing the work of Jiang et al. i.e., "ref_model.m", I am getting this error: Unrecognized function or variable 'featuresCalc_v2'.

I request you to kindly guide me.

**Comment by datngo93** [comment]
Sorry for my mistake!

I have updated the "source code" folder so that the "ref_model" function is now ready to execute.

**Comment by kumarballapavan** [comment]
It is working now. Thank you.
